services:
  node0:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['0', 'leader']
    networks:
    - edge-0-3
    - edge-0-6
    - edge-0-1
  node1:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['1']
    networks:
    - edge-1-7
    - edge-1-2
    - edge-0-1
  node2:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['2']
    networks:
    - edge-1-2
  node3:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['3']
    networks:
    - edge-3-4
    - edge-3-5
    - edge-0-3
  node4:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['4']
    networks:
    - edge-3-4
  node5:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['5']
    networks:
    - edge-5-9
    - edge-3-5
  node6:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['6']
    networks:
    - edge-6-8
    - edge-0-6
  node7:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['7']
    networks:
    - edge-1-7
  node8:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['8']
    networks:
    - edge-6-8
  node9:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['9']
    networks:
    - edge-5-9
networks:
  edge-6-8:
  edge-3-4:
  edge-5-9:
  edge-3-5:
  edge-1-7:
  edge-1-2:
  edge-0-3:
  edge-0-6:
  edge-0-1:
